name: publish to nuget
on:
  release:
    types: [created]
    
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Noticia.AspNetCore.AuthorizationEvaluationMiddleware/Noticia.AspNetCore.AuthorizationEvaluationMiddleware.csproj
          PACKAGE_NAME: Noticia.AspNetCore.AuthorizationEvaluationMiddleware
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$